### ISSUE TITLE
[Cog 1661] New OpenMPT plugin not correctly gated by OS version number

### ISSUE THREAD

**Issue by skabmedia** [losnoco/Cog#190]
Crashes immediately when trying to play ProTracker MODs.

Apprarently regression, older versions (last I had at hand was 1638) work just fine.

**Comment by kode54** [comment]
Please post a crash log.

**Comment by skabmedia** [comment]
Ah, there it is:

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Cog.app/Contents/PlugIns/OpenMPT.bundle/Contents/MacOS/../Frameworks/libOpenMPT.framework/Versions/A/libOpenMPT (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

I'm still on 10.13, so this library was built with the wrong (for 10.13) SDK. libopenmpt by itself still works fine on 10.13, so ideally the solution should be a flick of a switch.

**Comment by kode54** [comment]
Does this crash, or does it simply not load that plugin? It should be loading the OpenMPTOld plugin regardless.

**Comment by skabmedia** [comment]
I noticed that "old" Plugin, but no, it still tries to use the incompatible one (build 1664) and bombs:

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Cog.app/Contents/PlugIns/OpenMPT.bundle/Contents/MacOS/../Frameworks/libOpenMPT.framework/Versions/A/libOpenMPT (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Cog.app/Contents/PlugIns/OpenMPT.bundle/Contents/MacOS/../Frameworks/libOpenMPT.framework/Versions/A/libOpenMPT (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by kode54** [comment]
Yeah, sorry about that. I've now version gated the plugins completely now. They'll still both load, but only the correct one will be added to the loaded plugins class lists. Expect a fix in version 1666, when that's uploaded.

**Comment by kode54** [comment]
@skabmedia Can you please verify this is fixed now?

**Comment by skabmedia** [comment]
Sorry for the delay, yes, it seems to work now (build 1748, you've been busy ;-)).

I just checked what the problem with libopenmpt 0.6 was and indeed it doesn't build on my 10.13 system anymore, so thanks for still supporting us old-Mac-users!

**Comment by kode54** [comment]
Yeah, libopenmpt 0.6 requires libc++ features that weren't implemented in the OS until 10.15.

**Comment by kode54** [comment]
Speaking of old-Mac-users, I just added libfdk-aac to the mix, so now there's USAC support on 10.14.x and older as well.
